In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import isaacgym
import isaacgymenvs
from isaacgymenvs.utils.reformat import omegaconf_to_dict, print_dict
from isaacgymenvs.utils.utils import set_np_formatting, set_seed
from isaacgymenvs.utils.rlgames_utils import RLGPUEnv, RLGPUAlgoObserver, get_rlgames_env_creator

from rl_games.common import env_configurations, vecenv
from rl_games.torch_runner import Runner
from rl_games.algos_torch import model_builder

from omegaconf import DictConfig, OmegaConf

import torch
import numpy as np
import matplotlib.pyplot as plt

from vecrobotics import *
from qp_utils import *

from fista import FISTA, ForceQP

Importing module 'gym_38' (/home/hz/devel/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/hz/devel/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json


PyTorch version 2.0.0
Device count 1
/home/hz/devel/isaacgym/python/isaacgym/_bindings/src/gymtorch


Using /home/hz/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/hz/.cache/torch_extensions/py38_cu117/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module gymtorch...
2023-05-16 18:03:50,790 - INFO - logger - logger initialized


Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html


<unknown>:3: DeprecationWarning: invalid escape sequence \*
/home/hz/miniforge3/envs/rlgpu/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(


In [3]:
cfg = OmegaConf.load("../isaacgymenvs/cfg/config.yaml")
cfg.task_name = "TrifingerNYU"
cfg.num_envs = 4
cfg.task = OmegaConf.load("../isaacgymenvs/cfg/task/TrifingerNYU.yaml")
cfg.task.env.command_mode = "fingertip_diff_force"
cfg.headless = True

In [4]:
def create_env_thunk(**kwargs):
    envs = isaacgymenvs.make(
            cfg.seed, 
            cfg.task_name, 
            cfg.task.env.numEnvs, 
            cfg.sim_device,
            cfg.rl_device,
            cfg.graphics_device_id,
            cfg.headless,
            cfg.multi_gpu,
            cfg.capture_video,
            cfg.force_render,
            cfg,
            **kwargs,
        )
    return envs

In [5]:
device = cfg.sim_device
envs = create_env_thunk()

/home/hz/miniforge3/envs/rlgpu/lib/python3.8/site-packages/gym/spaces/box.py:112: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/hz/learning/IsaacGymEnvs/isaacgymenvs/tasks/trifingerNYU.py:1291: DeprecationWarning: an integer is required (got type isaacgym._bindings.linux-x86_64.gym_38.DofDriveMode).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  robot_asset_options.default_dof_drive_mode = gymapi.DOF_MODE_EFFORT


[Warning] [carb.gym.plugin] useGpu is set, forcing single scene (0 subscenes)
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Trifinger Robot Asset: 
	 Number of bodies: 23
	 Number of shapes: 39
	 Number of dofs: 9
	 Number of actuated dofs: 9
Trifinger Table Asset: 
	 Number of bodies: 2
	 Number of shapes: 1
Trifinger Boundary Asset: 
	 Number of bodies: 1
	 Number of shapes: 41
Using VHACD cache directory '/home/hz/.isaacgym/vhacd'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/int_sim.stl'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/prox-sim.stl'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/tip_link_sim.stl'
Found existing co

In [6]:
lifting_data = np.load("data/lifting.npz", allow_pickle=True)["data"]

In [7]:
# get ftip states
envs.reset_idx(torch.arange(cfg.num_envs))
N = 570
action_buffer = torch.zeros(N, 18).to(device)
ftip_pos_buffer = torch.zeros(N, 3, 3).to(device)
ftip_pos_local_buffer = torch.zeros(N, 3, 3).to(device)
object_pose_buffer = torch.zeros(N, 7).to(device)
contact_normals_buffer = []

q_buffer = torch.zeros(N, 9).to(device)
dq_buffer = torch.zeros(N, 9).to(device)
obs, rwds, resets, info = envs.step(torch.zeros(cfg.num_envs, 18))

In [8]:
# def get_cube_contact_normals(ftip_pos, threshold=0.0435):
#     batch_size = len(ftip_pos)
#     contact_normals = torch.zeros(batch_size, 3).to(ftip_pos.device)
        
#     _, max_indices = torch.max(torch.abs(ftip_pos), dim=1)
#     max_values = torch.squeeze(torch.gather(ftip_pos, 1, max_indices.unsqueeze(1)))

#     mask_pos = (torch.abs(max_values) <= threshold) * (max_values > 0)
#     mask_neg = (torch.abs(max_values) <= threshold) * (max_values < 0)

#     # contact normal points to the same direction as the contact force, hence into the object
#     contact_normals[mask_pos, max_indices[mask_pos]] = -1.0
#     contact_normals[mask_neg, max_indices[mask_neg]] = 1.0
    
#     return contact_normals

# def get_contact_frame_orn(contact_normals: torch.Tensor):
#     # get the orientation of the contact frames expressed in the object frame
#     z_axis = contact_normals
#     zero_indices = torch.argmax(torch.eq(z_axis, 0).int(), dim=1)
#     y_axis = torch.eye(3).to(z_axis.device)[zero_indices]
#     x_axis = torch.cross(y_axis, z_axis, dim=1)
#     y_axis = torch.cross(z_axis, x_axis, dim=1) # this makes sure if z is all zero, then orn is a zero matrix
#     orn = torch.stack((x_axis, y_axis, z_axis), dim=2)
#     return orn

# def hstacked_SO3_transform(mat, vec):
#     batch_size, d1, d2 = mat.shape
#     stack_size = d2 // 3
#     transformed = torch.zeros_like(vec)
#     for i in range(stack_size):
#         selection = torch.zeros_like(vec)
#         selection[:, 3*i:3*(i+1)] = 1
#         transformed[:, 3*i:3*(i+1)] = bmv(mat, vec * selection)
#     return transformed

# def get_force_qp_data(ftip_pos, object_pose, mg, weights=[1, 200, 1e-4]):
#     # get ftip positin in the object frame
#     batch_size, num_ftip, _ = ftip_pos.shape
#     p = SE3_inverse_transform(object_pose.repeat_interleave(3, dim=0), 
#                     ftip_pos.view(-1, 3))
#     contact_normals = get_cube_contact_normals(p)
#     R = get_contact_frame_orn(contact_normals)
#     R_vstacked = R.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
#     Q1 = R_vstacked @ R_vstacked.transpose(1, 2)
    
#     pxR = vec2skewsym_mat(p) @ R
#     pxR_vstacked = pxR.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
#     Q2 = pxR_vstacked @ pxR_vstacked.transpose(1, 2)
    
#     w1, w2, w3 = weights
#     Q = w1 * Q1 + w2 * Q2 + w3 * torch.eye(3 * num_ftip).repeat(batch_size, 1, 1).to(Q1.device)

#     # for Q == 0, hence R1, R2, R3 == 0, fill the diagnoal of Q with ones. This produces f == 0
#     reshaped_tensor = Q.view(batch_size, -1)
#     diagonal_elements_zero = torch.all(reshaped_tensor[:, ::num_vars+1] == 0, dim=1)
#     mask = diagonal_elements_zero[:, None].repeat(1, num_vars)
#     diag_idx = torch.arange(num_vars)
#     Q[:, diag_idx, diag_idx] = Q[:, diag_idx, diag_idx].masked_fill_(mask, 1)
    
#     object_orn = quat2mat(object_pose[:, 3:])
#     mg_local = bmv(object_orn.transpose(1,2), mg)
#     q = -2 * bmv(R_vstacked, mg_local)
    
#     return Q, q, R_vstacked, pxR_vstacked, contact_normals

In [9]:
# construct force QP
batch_size = cfg.num_envs
num_vars = 9
lb = -10 * torch.ones(batch_size, num_vars)
ub = 10 * torch.ones(batch_size, num_vars)
mg = torch.tensor([0, 0, 9.81]).repeat(batch_size, 1).to(device)
cost_weights = [1, 200, 1e-4]

prob = ForceQP(batch_size, num_vars, friction_coeff=1.0, device=device)
solver = FISTA(prob, device=device)
max_it = 50

for n in range(N):
    q = envs._dof_position
    dq = envs._dof_velocity
    q_buffer[n] = q[0]
    dq_buffer[n] = dq[0]
    
    ftip_state = envs._rigid_body_state[:, envs._fingertip_indices]
    ftip_pos = ftip_state[:, :, 0:3]
    ftip_pos_buffer[n] = ftip_pos[0]
    
    object_pose = envs._object_state_history[0][:, 0:7]
    object_orn = quat2mat(object_pose[:, 3:])
    object_pose_buffer[n] = object_pose[0]
        
    # set up force qp
    Q, q, R_vstacked, pxR_vstacked, contact_normals = get_force_qp_data(ftip_pos, object_pose, mg,  cost_weights)    
    prob.set_data(Q, q, lb, ub)
    solver.reset()
    for i in range(max_it):
        solver.step()
    ftip_force_contact_frame = solver.prob.yk.clone()
    contact_normals_buffer.append(contact_normals)
    
    # convert force to the world frame
    R = R_vstacked.reshape(-1, 3, 3).transpose(1, 2)
    ftip_force_object_frame = stacked_bmv(R, ftip_force_contact_frame)
    ftip_force_des = stacked_bmv(object_orn.repeat(3, 1, 1), ftip_force_object_frame)
    ftip_pos_des = torch.tensor(lifting_data[20 * n]['policy']['controller']['ft_pos_des'], dtype=torch.float32).to(device)
    
    action = torch.zeros(cfg.num_envs, 18)
    action[:, :9] = ftip_pos_des.view(1, 9).repeat(cfg.num_envs, 1) - ftip_pos.reshape(cfg.num_envs, 9)
    
    if n >= 300:
        action[:, 9:] = ftip_force_des
    
    action_buffer[n] = action[0]
    obs, rwds, resets, info = envs.step(action)

In [10]:
lifting_data[20 * n]['object_position']

array([ 0.00253385, -0.01002879,  0.0794745 ])

In [11]:
object_pose[:, :3]

tensor([[ 0.0050, -0.0114,  0.0604],
        [ 0.0090, -0.0096,  0.0722],
        [ 0.0084, -0.0102,  0.0714],
        [ 0.0087, -0.0095,  0.0725]], device='cuda:0')

In [12]:
ftip_force_des.view(-1, 3, 3).sum(dim=1)

tensor([[-1.7603, -0.3173,  7.8980],
        [ 1.2175,  1.5135, 10.4925],
        [ 0.5733, -2.8362,  9.1764],
        [ 0.1510,  0.3002,  9.9460]], device='cuda:0')