In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import isaacgym
import isaacgymenvs
from isaacgymenvs.utils.reformat import omegaconf_to_dict, print_dict
from isaacgymenvs.utils.utils import set_np_formatting, set_seed
from isaacgymenvs.utils.rlgames_utils import RLGPUEnv, RLGPUAlgoObserver, get_rlgames_env_creator

from rl_games.common import env_configurations, vecenv
from rl_games.torch_runner import Runner
from rl_games.algos_torch import model_builder

from omegaconf import DictConfig, OmegaConf

import torch
import numpy as np
import matplotlib.pyplot as plt

from isaacgymenvs.qp.fista import ForceQP, LocationQP, FISTA
from isaacgymenvs.qp.qp_utils import *
from isaacgymenvs.qp.vecrobotics import *

Importing module 'gym_38' (/home/hz/devel/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/hz/devel/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json


PyTorch version 2.0.0
Device count 1
/home/hz/devel/isaacgym/python/isaacgym/_bindings/src/gymtorch


Using /home/hz/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/hz/.cache/torch_extensions/py38_cu117/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module gymtorch...
2023-06-13 16:03:50,237 - INFO - logger - logger initialized


Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html


<unknown>:3: DeprecationWarning: invalid escape sequence \*
/home/hz/miniforge3/envs/rlgpu/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(


In [3]:
cfg = OmegaConf.load("../isaacgymenvs/cfg/config.yaml")
cfg.task_name = "TrifingerNYU"
cfg.num_envs = 4
cfg.task = OmegaConf.load("../isaacgymenvs/cfg/task/TrifingerNYU.yaml")

cfg.task.env.command_mode = "torque"
cfg.task.env.enable_location_qp = False
cfg.task.env.reset_distribution.object_initial_state.type = "default"
cfg.task.normalize_action = False
cfg.headless = False

In [4]:
def create_env_thunk(**kwargs):
    envs = isaacgymenvs.make(
            cfg.seed, 
            cfg.task_name, 
            cfg.task.env.numEnvs, 
            cfg.sim_device,
            cfg.rl_device,
            cfg.graphics_device_id,
            cfg.headless,
            cfg.multi_gpu,
            cfg.capture_video,
            cfg.force_render,
            cfg,
            **kwargs,
        )
    return envs

In [5]:
lifting_data = np.load("data/lifting2.npz", allow_pickle=True)["data"]

In [6]:
device = cfg.sim_device
envs = create_env_thunk()

/home/hz/miniforge3/envs/rlgpu/lib/python3.8/site-packages/gym/spaces/box.py:112: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/hz/learning/IsaacGymEnvs/isaacgymenvs/tasks/trifingerNYU.py:1389: DeprecationWarning: an integer is required (got type isaacgym._bindings.linux-x86_64.gym_38.DofDriveMode).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  robot_asset_options.default_dof_drive_mode = gymapi.DOF_MODE_EFFORT


[Warning] [carb.gym.plugin] useGpu is set, forcing single scene (0 subscenes)
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Trifinger Robot Asset: 
	 Number of bodies: 23
	 Number of shapes: 39
	 Number of dofs: 9
	 Number of actuated dofs: 9
Trifinger Table Asset: 
	 Number of bodies: 2
	 Number of shapes: 1
Trifinger Boundary Asset: 
	 Number of bodies: 1
	 Number of shapes: 41
Using VHACD cache directory '/home/hz/.isaacgym/vhacd'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/int_sim.stl'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/prox-sim.stl'
Found existing convex decomposition for mesh '/home/hz/learning/IsaacGymEnvs/isaacgymenvs/../assets/trifinger/robot_properties_fingers/meshes/pro/tip_link_sim.stl'
Found existing co

In [7]:
def get_force_qp_data(ftip_pos: torch.Tensor, object_pose: torch.Tensor, 
                      total_force_des: torch.Tensor, torque_ref: torch.Tensor, jacobian: torch.Tensor,
                      weights: List[float]):
    # get ftip positin in the object frame
    batch_size, num_ftip, _ = ftip_pos.shape
    num_vars = num_ftip * 3

    p = SE3_inverse_transform(object_pose.repeat_interleave(3, dim=0), ftip_pos.view(-1, 3))
    contact_normals = get_cube_contact_normals(p)
    object_orn = quat2mat(object_pose[:, 3:])
    jacobian_transpose = torch.transpose(jacobian, 1, 2)
    
    
    # force cost
    R = get_contact_frame_orn(contact_normals)
    R_vstacked = R.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
    Q1 = R_vstacked @ R_vstacked.transpose(1, 2)
    total_force_des_object_frame = bmv(object_orn.transpose(1,2), total_force_des)
    q1 = -2 * bmv(R_vstacked, total_force_des_object_frame)
    
    # torque cost
    pxR = vec2skewsym_mat(p) @ R
    pxR_vstacked = pxR.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
    Q2 = pxR_vstacked @ pxR_vstacked.transpose(1, 2)
    
    # joint torque cost
    R_reshaped = R.view(batch_size, num_ftip, 3, 3)
    R_diag = torch.zeros(batch_size, 9, 9).to(ftip_pos.device)
    for i in range(num_ftip):
        R_diag[:, i*3:i*3 + 3, i*3:i*3 + 3] = R_reshaped[:, i]
    object_orn_diag = torch.zeros(batch_size, 9, 9).to(ftip_pos.device)
    for i in range(num_ftip):
        object_orn_diag[:, i*3:i*3 + 3, i*3:i*3 + 3] = object_orn
    A = jacobian_transpose @ object_orn_diag @ R_diag
    Q3 = torch.transpose(A, 1, 2) @ A
    q3 = -2 * bmv(A, torque_ref)
    
    # regularization
    Q4 = 1e-4 * torch.eye(3 * num_ftip).repeat(batch_size, 1, 1).to(ftip_pos.device)
    
    # If any of contact normals == 0, set the desired force and torque weights to zero
    reshaped_tensor = Q1.view(batch_size, -1)
    mask = torch.any(reshaped_tensor[:, ::num_vars+1] == 0, dim=1)

    # construct total cost
    weights = torch.tensor(weights, dtype=torch.float32, device=ftip_pos.device).repeat(batch_size, 1)
    w1, w2, w3 = weights.split(1, dim=1)
    w1[mask] = 0
    w2[mask] = 0
    w3[mask] = 0
    
    q = w1*q1 + w3*q3
    
    w1 = w1.view(batch_size, 1, 1)
    w2 = w2.view(batch_size, 1, 1)
    w3 = w3.view(batch_size, 1, 1)
    
    Q = w1 * Q1 + w2 * Q2 + w3 * Q3 + Q4
    
    return Q, q, R_vstacked, pxR_vstacked, contact_normals

In [8]:
# get ftip states
envs.reset_idx(torch.arange(cfg.num_envs))
N = 700
action_buffer = torch.zeros(N, 9).to(device)
projected_torque_buffer = torch.zeros(N, 9).to(device)

ftip_pos_buffer = torch.zeros(N, 3, 3).to(device)
ftip_pos_local_buffer = torch.zeros(N, 3, 3).to(device)
object_pose_buffer = torch.zeros(N, 7).to(device)
contact_normals_buffer = []

q_buffer = torch.zeros(N, 9).to(device)
dq_buffer = torch.zeros(N, 9).to(device)
obs, rwds, resets, info = envs.step(torch.zeros(cfg.num_envs, 9))

In [9]:
# construct force QP
batch_size = cfg.num_envs
num_vars = 9
force_lb = -1.5 * torch.ones(batch_size, num_vars)
force_ub = 1.5 * torch.ones(batch_size, num_vars)

force_qp = ForceQP(batch_size, num_vars, friction_coeff=1.0, device=device)
force_qp_solver = FISTA(force_qp, device=device)
max_it = 20

for n in range(N):
    q = envs._dof_position
    dq = envs._dof_velocity
    q_buffer[n] = q[0]
    dq_buffer[n] = dq[0]
    
    ftip_state = envs._rigid_body_state[:, envs._fingertip_indices]
    ftip_pos = ftip_state[:, :, 0:3]
    ftip_vel = ftip_state[:, :, 7:10]
    ftip_pos_buffer[n] = ftip_pos[0]
    
    object_pose = envs._object_state_history[0][:, 0:7]
    object_position = object_pose[:, 0:3]
    desired_object_position = envs._desired_object_poses_buf[:, 0:3]
    object_orn = quat2mat(object_pose[:, 3:])
    object_pose_buffer[n] = object_pose[0]
    
    time_idx = 0 if n < 200 else 20 * (n - 200)
    ftip_pos_des = torch.tensor(lifting_data[time_idx]['policy']['controller']['ft_pos_des'], dtype=torch.float32).to(device)
    ftip_vel_des = torch.tensor(lifting_data[time_idx]['policy']['controller']['ft_vel_des'], dtype=torch.float32).to(device)

    ftip_pos_diff = ftip_pos_des - ftip_pos.reshape(cfg.num_envs, 9)
    ftip_vel_diff = ftip_vel_des - ftip_vel.reshape(cfg.num_envs, 9)
    
    task_space_force = torch.tensor([200,200,200]*3, dtype=torch.float32, device=envs.device) * ftip_pos_diff
    task_space_force += torch.tensor([5]*9, dtype=torch.float32, device=envs.device)  * ftip_vel_diff
    
    jacobian = envs.get_fingertip_jacobian_linear()
    jacobian_transpose = torch.transpose(jacobian, 1, 2)
    
#     action = -0.36 + 0.72 * torch.rand(cfg.num_envs, 9).to(device)
#     task_space_force = -1.5 + 3. * torch.rand(cfg.num_envs, 9).to(device)
    
    torque_ref = bmv(jacobian_transpose, task_space_force)
    
    desired_object_acceleration = 10 * (desired_object_position - object_position)
    desired_object_acceleration += torch.tensor([0, 0, 9.81]).to(desired_object_acceleration.device)
    total_force_des = 0.08 * desired_object_acceleration
    force_qp_cost_weights = [1, 200, 0.01]
    Q, q, R_vstacked, pxR_vstacked, contact_normals = get_force_qp_data(ftip_pos, 
                                                                        object_pose,
                                                                        total_force_des,
                                                                        torque_ref, 
                                                                        jacobian,
                                                                        force_qp_cost_weights)
    
    force_qp_solver.prob.set_data(Q, q, force_lb, force_ub)
    force_qp_solver.reset()
    for i in range(max_it):
        force_qp_solver.step()
    ftip_force_contact_frame = force_qp_solver.prob.yk.clone()

    # convert force to the world frame
    R = R_vstacked.reshape(-1, 3, 3).transpose(1, 2)
    ftip_force_object_frame = stacked_bmv(R, ftip_force_contact_frame)
    object_orn = quat2mat(object_pose[:, 3:7]).repeat(3, 1, 1)
    task_space_force2 = stacked_bmv(object_orn, ftip_force_object_frame)
    
    action = torque_ref + bmv(jacobian_transpose, task_space_force2)
    
    action_buffer[n] = action[0]
#     projected_torque_buffer[n] = projected_torque[0]
    obs, rwds, resets, info = envs.step(action)

In [10]:
# weights = force_qp_cost_weights
# # get ftip positin in the object frame
# batch_size, num_ftip, _ = ftip_pos.shape
# num_vars = num_ftip * 3

# p = SE3_inverse_transform(object_pose.repeat_interleave(3, dim=0), ftip_pos.view(-1, 3))
# contact_normals = get_cube_contact_normals(p)
# object_orn = quat2mat(object_pose[:, 3:])
# jacobian_transpose = torch.transpose(jacobian, 1, 2)


# # force cost
# R = get_contact_frame_orn(contact_normals)
# R_vstacked = R.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
# Q1 = R_vstacked @ R_vstacked.transpose(1, 2)
# total_force_des_object_frame = bmv(object_orn.transpose(1,2), total_force_des)
# q1 = -2 * bmv(R_vstacked, total_force_des_object_frame)

# # torque cost
# pxR = vec2skewsym_mat(p) @ R
# pxR_vstacked = pxR.transpose(1, 2).reshape(-1, 3 * num_ftip, 3)
# Q2 = pxR_vstacked @ pxR_vstacked.transpose(1, 2)

# # joint torque cost
# R_reshaped = R.view(batch_size, num_ftip, 3, 3)
# R_diag = torch.zeros(batch_size, 9, 9).to(ftip_pos.device)
# for i in range(num_ftip):
#     R_diag[:, i*3:i*3 + 3, i*3:i*3 + 3] = R_reshaped[:, i]
# object_orn_diag = torch.zeros(batch_size, 9, 9).to(ftip_pos.device)
# for i in range(num_ftip):
#     object_orn_diag[:, i*3:i*3 + 3, i*3:i*3 + 3] = object_orn
# A = jacobian_transpose @ object_orn_diag @ R_diag
# Q3 = torch.transpose(A, 1, 2) @ A
# q3 = -2 * bmv(A, action)

# # regularization
# Q4 = 1e-4 * torch.eye(3 * num_ftip).repeat(batch_size, 1, 1).to(ftip_pos.device)

# # If any of contact normals == 0, set the desired force and torque weights to zero
# reshaped_tensor = Q1.view(batch_size, -1)
# mask = torch.any(reshaped_tensor[:, ::num_vars+1] == 0, dim=1)

# # construct total cost
# weights = torch.tensor(weights, dtype=torch.float32, device=ftip_pos.device).repeat(batch_size, 1)
# w1, w2, w3 = weights.split(1, dim=1)
# w1[mask] = 0
# w2[mask] = 0
# w3[mask] = 0

# q = w1*q1 + w3*q3

# w1 = w1.view(batch_size, 1, 1)
# w2 = w2.view(batch_size, 1, 1)
# w3 = w3.view(batch_size, 1, 1)

# Q = w1 * Q1 + w2 * Q2 + w3 * Q3 + Q4

In [11]:
task_space_force[:, :3] + task_space_force[:, 3:6] + task_space_force[:, 6:]

tensor([[-0.4914, -0.2504,  9.3608],
        [-0.4103, -0.2710,  9.2257],
        [-0.4721, -0.3734,  9.3450],
        [-0.4516, -0.3525,  9.3456]], device='cuda:0')

In [12]:
task_space_force2[:, :3] + task_space_force2[:, 3:6] + task_space_force2[:, 6:]

tensor([[-0.0128, -0.0326,  0.7052],
        [-0.0741, -0.0496,  0.7072],
        [ 0.0122, -0.0397,  0.7281],
        [-0.0275,  0.0316,  0.7336]], device='cuda:0')

In [13]:
total_force_des

tensor([[ 0.0349, -0.0238,  0.7852],
        [-0.0322, -0.0329,  0.7891],
        [ 0.0041, -0.0212,  0.8120],
        [ 0.0098,  0.0459,  0.7991]], device='cuda:0')

In [14]:
torque_ref

tensor([[-0.0737, -0.5522, -0.7387,  0.3294, -0.0348, -0.2960, -0.3685,  0.2139,
         -0.2433],
        [-0.1334, -0.5498, -0.7516,  0.3453, -0.0424, -0.2843, -0.3636,  0.2557,
         -0.2209],
        [-0.1297, -0.5467, -0.7616,  0.3587, -0.0647, -0.2944, -0.3166,  0.2792,
         -0.1994],
        [-0.0424, -0.5596, -0.7487,  0.3585, -0.0368, -0.2888, -0.3139,  0.2134,
         -0.2230]], device='cuda:0')

In [15]:
action

tensor([[-0.0836, -0.6991, -0.8842,  0.4351, -0.1077, -0.3821, -0.3774,  0.2495,
         -0.1668],
        [-0.1313, -0.6965, -0.8941,  0.4448, -0.1131, -0.3680, -0.3752,  0.2904,
         -0.1482],
        [-0.1381, -0.7007, -0.9130,  0.4659, -0.1300, -0.3768, -0.3314,  0.3126,
         -0.1250],
        [-0.0491, -0.7141, -0.9002,  0.4722, -0.1099, -0.3749, -0.3360,  0.2446,
         -0.1498]], device='cuda:0')

In [16]:
task_space_force2

tensor([[ 4.8009e-02, -6.5955e-01,  6.6094e-01,  5.5346e-02,  6.2345e-01,
          6.0599e-01, -1.1617e-01,  3.5135e-03, -5.6169e-01],
        [-4.6900e-04, -6.5746e-01,  6.5668e-01,  4.6350e-02,  5.9382e-01,
          5.8603e-01, -1.2001e-01,  1.4013e-02, -5.3553e-01],
        [ 4.4899e-02, -6.8762e-01,  6.8902e-01,  8.7532e-02,  6.1315e-01,
          6.0062e-01, -1.2021e-01,  3.4748e-02, -5.6153e-01],
        [ 3.1576e-02, -6.9115e-01,  6.9037e-01,  7.2784e-02,  6.5625e-01,
          6.1220e-01, -1.3182e-01,  6.6553e-02, -5.6895e-01]], device='cuda:0')

In [17]:
zero_rows = (task_space_force2.sum(dim=1) == 0)  # find rows in M1 that are all zeros
task_space_force2[zero_rows] = task_space_force[zero_rows]  

In [18]:
task_space_force2

tensor([[ 4.8009e-02, -6.5955e-01,  6.6094e-01,  5.5346e-02,  6.2345e-01,
          6.0599e-01, -1.1617e-01,  3.5135e-03, -5.6169e-01],
        [-4.6900e-04, -6.5746e-01,  6.5668e-01,  4.6350e-02,  5.9382e-01,
          5.8603e-01, -1.2001e-01,  1.4013e-02, -5.3553e-01],
        [ 4.4899e-02, -6.8762e-01,  6.8902e-01,  8.7532e-02,  6.1315e-01,
          6.0062e-01, -1.2021e-01,  3.4748e-02, -5.6153e-01],
        [ 3.1576e-02, -6.9115e-01,  6.9037e-01,  7.2784e-02,  6.5625e-01,
          6.1220e-01, -1.3182e-01,  6.6553e-02, -5.6895e-01]], device='cuda:0')